import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import WithNavbarAndFooter from "./_components/navigation/WithNavbarAndFooter";

export const metadata: Metadata = {
  title: "Axiom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <WithNavbarAndFooter>
          {children}
          <Toaster />
        </WithNavbarAndFooter>
      </body>
    </html>
  );
}
